[tox]
envlist = clean, test-py{310,311,312,313,314}, coverage, lint

[testenv:clean]
skip_install = true
allowlist_externals = sh
commands =
  sh -c 'rm -rf {work_dir}/.coverage {work_dir}/.coverage* {work_dir}/htmlcov {work_dir}/coverage.xml'

[testenv:test-py{310,311,312,313,314}]
depends = clean
runner = uv-venv-lock-runner
dependency_groups = test
setenv =
  COVERAGE_FILE = {work_dir}/.coverage.{envname}
  COVERAGE_CONTEXT = {envname}
commands =
  pytest -v --cov --cov-report= {posargs}

[testenv:coverage]
depends = test-py{310,311,312,313,314}
deps =
  coverage[toml]
skip_install = true
setenv =
  COVERAGE_FILE = {work_dir}/.coverage
commands =
  coverage combine --keep
  coverage html -d {work_dir}/htmlcov
  coverage xml -o {work_dir}/coverage.xml
  coverage report

[testenv:lint]
basepython = python3.10
runner = uv-venv-lock-runner
dependency_groups = lint
ignore_errors = true
commands =
  ruff check --no-fix .
  ruff format --check .
  ty check
  pyright --verifytypes attributes_doc
